version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/react-app-test/
hooks:
  Install:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 3000
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 3000