version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/npm-before-install.sh
      runas: root
      timeout: 3000
  Install:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 3000
  AfterInstall:
    - location: scripts/npm-after-install.sh
      runas: root
      timeout: 3000
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 3000